source ~/.local/share/omakub/configs/bash/shell
source ~/.local/share/omakub/configs/bash/aliases
source ~/.local/share/omakub/configs/bash/init

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
