foreground         #c4cacf
background         #152c41
background_opacity 1.0
cursor             #c4cacf

active_tab_foreground     #152c41
active_tab_background     #c4cacf
inactive_tab_foreground   #c4cacf
inactive_tab_background   #152c41

active_border_color   #c4cacf
inactive_border_color #152c41
bell_border_color     #35BAC3

color0       #152c41
color8       #687480
color1       #35BAC3
color9       #35BAC3
color2       #4BBDC2
color10      #4BBDC2
color3       #62C4C2
color11      #62C4C2
color4       #D1A5A0
color12      #D1A5A0
color5       #A2CABD
color13      #A2CABD
color6       #E3D5BB
color14      #E3D5BB
color7       #c4cacf
color15      #c4cacf
