foreground         #c3c6c8
background         #0f1b24
background_opacity 1.0
cursor             #c3c6c8

active_tab_foreground     #0f1b24
active_tab_background     #c3c6c8
inactive_tab_foreground   #c3c6c8
inactive_tab_background   #0f1b24

active_border_color   #c3c6c8
inactive_border_color #0f1b24
bell_border_color     #2F7587

color0       #0f1b24
color8       #5e6a74
color1       #2F7587
color9       #2F7587
color2       #517985
color10      #517985
color3       #368C98
color11      #368C98
color4       #5D999B
color12      #5D999B
color5       #72BFBC
color13      #72BFBC
color6       #9CA69A
color14      #9CA69A
color7       #c3c6c8
color15      #c3c6c8
