#!/bin/bash

# Terminal packages (ALL REQUIRED)
# Format: "command_name:package1 package2 package3"
TERMINAL_PACKAGES=(
  "nvim:neovim tree-sitter luarocks"
  "lazygit:lazygit"
  "yazi:yazi"
  "gh:github-cli"
  "fastfetch:fastfetch"
  "starship:starship"
  "atuin:atuin"
  "opencode:opencode-bin"
  "fzf:fzf"
  "rg:ripgrep"
  "fd:fd"
  "bat:bat"
  "eza:eza"
  "zoxide:zoxide"
  "jq:jq"
  "tree:tree"
  "btop:btop"
  "magick:imagemagick"
  "tmux:tmux tmux-plugin-manager"
  "sesh:sesh-bin"
  "gitmux:gitmux-bin"
  "docker:docker docker-compose"
  "lazydocker:lazydocker"
  "kubectl:kubectl"
  "krew:krew"
  "helm:helm"
  "kubectx:kubectx"
  "vault:vault"
)
